name: CICD Actions
on:
  push:
    branches:
      - main
jobs:
  Username-Branch-Repository:
    runs-on: ubuntu-latest
    steps:
      - run: echo "My user name is ${{ github.actor }}" 
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of my branch is ${{ github.ref }} and my repository is ${{ github.repository }}."
    
  docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Login en DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build
        run: docker build -t ${{ vars.DOCKER_USER }}/back-examen-img:latest .
      - name: Push
        run: docker push ${{ vars.DOCKER_USER }}/back-examen-img:latest

  image-to-github:
    runs-on: ubuntu-latest
    needs: docker-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/nasuandrea/examen-back/back-examen:latest
